fix file_location bug
mitodl/ocw-data-parser pull request #104
Opened 2020-12-03 19:19 UTC by gumaerc

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-data-parser/issues/103
Closes https://github.com/mitodl/hugo-course-publisher/issues/422
Closes https://github.com/mitodl/ocw-to-hugo/issues/137

#### What's this PR do?
This PR fixes a bug with regenerating parsed JSON in which in some cases the `file_location` property of items in the `course_files` array to be missing.  This change sets them to the proper S3 url if S3 uploading is set up, or simply to the filename.

#### How should this be manually tested?
Parse any of the following courses:

```
"11-943j-urban-transportation-land-use-and-the-environment-spring-2002",
"16-885j-aircraft-systems-engineering-fall-2004"
"16-891j-space-policy-seminar-spring-2003",
"18-024-multivariable-calculus-with-theory-spring-2011"
"21m-380-music-and-technology-sound-design-spring-2016",
"res-18-001-calculus-online-textbook-spring-2005"
"res-18-006-calculus-revisited-single-variable-calculus-fall-2010",
"sts-003-the-rise-of-modern-science-fall-2010"
"sts-471j-engineering-apollo-the-moon-project-as-a-complex-system-spring-2007",
```
In the parsed JSON output, ensure that every item in `course_files` has a `file_location` attribute.

2020-12-03 22:00 UTC, noisecapella requested changes

2020-12-03 22:00 UTC, noisecapella commented on ocw_data_parser/ocw_data_parser.py
> +        file_location = urljoin(bucket_base_url, os.path.join(course_id, file_name))
This seems to be adding the course id twice. For example: `https://open-learning-course-data-ci.s3.amazonaws.com/11-943j-urban-transportation-land-use-and-the-environment-spring-2002/11-943j-urban-transportation-land-use-and-the-environment-spring-2002/11-943js02.jpg`

2020-12-03 22:00 UTC, noisecapella commented on ocw_data_parser/ocw_data_parser_test.py
> +        'file_location': '182.png'
Can we add a test which uses the `bucket_base_url` branch in `_compose_media_dict`?

2020-12-03 23:12 UTC, gumaerc commented
back to you @noisecapella

2020-12-04 14:28 UTC, noisecapella commented
The URL isn't working for me. For example I am seeing this link locally which is broken: https://open-learning-course-data-ci.s3.amazonaws.com/21m-380-music-and-technology-sound-design-spring-2016/MIT21M_380S16_lec_slides.pdf 

but in the bucket the filename is `73bb2f51aa991effbdb315e9d49f8d08_MIT21M_380S16_lec_slides.pdf`. Do we need to add a uid or something like that?

2020-12-04 14:44 UTC, gumaerc commented
Ah yes, my bad.  It should definitely be prefixed with the uid like that.

2020-12-04 17:26 UTC, gumaerc commented
back to you @noisecapella

2020-12-07 16:27 UTC, noisecapella commented
That link is working but it points to a PNG file... I'll make a separate issue for it in case we are uploading the wrong file somewhere

2020-12-07 17:00 UTC, noisecapella approved these changes

2020-12-08 15:20 UTC, merged