parse aka_course_number into new_course_numbers
mitodl/ocw-data-parser pull request #140
Opened 2021-04-23 21:14 UTC by gumaerc

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-data-parser/issues/137

#### What's this PR do?
OCW Plone JSON exports include a field in the first file called `aka_course_number`, which is actually an array of objects.  The objects contain an old course number and information pertaining to the new course number including, the level (graduate / undergraduate) and a "sort by column."  This PR parses this field and renames the key to `new_course_numbers`.  The `aka_` prefix is removed from the keys in the object.  Since these objects serve as "updates" to the course number, it makes more sense to call it "new" and use "numbers" because there can be multiple updates.  To find the latest one, you would follow the chain starting at the course number listed directly on the course, finding the item in `new_course_numbers` where `old_course_number` matches that number and so on.

#### How should this be manually tested?
 - Convert a course with a populated `aka_course_number` field like `18-443-statistics-for-applications-spring-2015`
 - Verify that the `new_course_numbers` field looks right and makes sense

2021-04-26 14:51 UTC, noisecapella requested changes

2021-04-26 14:51 UTC, noisecapella commented on ocw_data_parser/ocw_data_parser.py
> +                    key.replace("aka_", ""): value
Can we do this replacment only if `aka_` is a prefix? This could cause problems if `aka_` appears elsewhere in the string

2021-04-26 17:32 UTC, gumaerc commented
@noisecapella all set

2021-04-27 13:35 UTC, noisecapella approved these changes

2021-04-27 21:01 UTC, merged